theme = "onedark_custom"

[editor]
# cursorline = true
color-modes = true
bufferline = "multiple"
cursorline = true
line-number = "relative"
file-picker.hidden = false
lsp.display-messages = true

indent-guides.render = true
indent-guides.character = "▏"

cursor-shape.insert = "bar"
cursor-shape.select = "underline"

gutters = [
	"diagnostics",
	"spacer",
	"line-numbers",
	"spacer",
	"diff",
	"spacer"
]

statusline.left = [
	"mode",
	"spacer",
	"spinner",
	"file-name",
	"read-only-indicator",
	"file-modification-indicator",
]

[keys.normal]
C-s = ":u"
C-q = ":q"
C-n = ":n"

C-w = ":bc"
C-tab = ":bn"
C-S-tab = ":bp"
C-r = ":config-reload"
del = "delete_selection_noyank"

x = "select_line_below"
X = "select_line_above"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

C-up = ["select_line_above", "delete_selection", "move_visual_line_up", "paste_before", "goto_line_start"]
C-down = ["select_line_above", "delete_selection", "paste_after", "goto_line_start"]

up = ["move_visual_line_up", "scroll_up" ]
down = ["move_visual_line_down", "scroll_down" ]

[keys.insert]
C-s = [":u", "normal_mode"]
C-tab = ":bn"
C-S-tab = ":bp"
C-del = "delete_word_forward"
C-backspace = "delete_word_backward"
C-z = "undo"
C-left = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_end", "move_char_right", "collapse_selection"]
