# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json

watch_stylesheet: true
watch_config: true
debug: false
update_check: true

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 8
      left: 12
      bottom: 8
      right: 12
    widgets:
      left:
        - "home"
        - "glazewm_workspaces"
        - "active_window"
      center:
        - "clock"
      right:
        - "notifications"
        - "wifi"
        - "media"
        - "battery"
        - "volume"

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\uf17a</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      monitor_exclusive: true
      enable_scroll_switching: true
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      animation: false

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 16
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 16
      thumbnail_corner_radius: 2
      thumbnail_edge_fade: true
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: false
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 100
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      scrolling_label:
        enabled: true
        update_interval_ms: 100
        style: "bounce" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "<span>\uf476</span> {count}"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon} Wifi"
      label_alt: "{wifi_icon} {wifi_name} {wifi_strength}%"
      update_interval: 10000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2b", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-24% strength
          "\udb82\udd22", # Icon for 25-49% strength
          "\udb82\udd25", # Icon for 50-74% strength
          "\udb82\udd28" # Icon for 75-100% strength
        ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | {power}W | {time_remaining}"
      update_interval: 10000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 30
        medium: 50
        high: 90
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      callbacks:
        on_left: ""
        on_right: "toggle_label"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
